### ISSUE TITLE
Project: Paraglide JS 2.0 (variants, pluralization, gendering)

### ISSUE THREAD

**Issue by samuelstroschein** [opral/inlang-paraglide-js#201]
### Context

This issue serves as "subscribe here to stay up to date with paraglide js 2.0".

### Changelog

- [X] supports for variants
- [X] builds on the inlang SDK v2 which uses sqlite
- https://github.com/opral/inlang-paraglide-js/issues/206

### Tasks/issues

See issues with the ["v2.0" label](https://github.com/opral/inlang-paraglide-js/issues?q=is%3Aopen+is%3Aissue+label%3Av2.0)

**Comment by juliomuhlbauer** [comment]
This could be fixed: https://github.com/opral/inlang-paraglide-js/issues/146 (it is really annoying.

**Comment by samuelstroschein** [comment]
@juliomuhlbauer added to the project that comes after paraglide js 2.0 (metaframework overhaul) https://github.com/opral/inlang-paraglide-js/issues/217

**Comment by samuelstroschein** [comment]
Progress is halted until the message format plugin, which most paraglide users use, is updated to v3 [https://github.com/opral/inlang-paraglide-js/issues/221](https://github.com/opral/inlang-paraglide-js/issues/221). While updating the message format to v3, the data model showed inconsistencies, see [https://github.com/opral/inlang-sdk/issues/195](https://github.com/opral/inlang-sdk/issues/195). 

Number 1 prio is to resolve the data model problems. Work on paralglide 2.0 will continue afterward

**Comment by samuelstroschein** [comment]
From discord https://discord.com/channels/897438559458430986/1094614450004303993/1286100529210064960

**End to end import, CRUD, export achieved**

Milestone achieved. We are now entering the phase of taking the observations from an end to end workflow to fix bugs and do adjustemnts where useful/required


Uploading CleanShot 2024-09-18 at 19.00.29.mp4…

**Comment by samuelstroschein** [comment]
Work on paraglide 2.0 continues. Might have a pre-release by the end of the day!

* the inlang sdk v2 is stable
* the message format plugin supports variants (!)

**Comment by samuelstroschein** [comment]
Logical tests are passing. TypeSafety is still a todo. Hence, no pre-release today and no prerelease until mid October. The team is meeting in Rome for an onsite next week which I a) have to attend and b) I have to prep :) 

 

<img src="https://uploads.linear.app/4cb6d418-86ee-4425-b5c8-f91266b0ab28/6d09ff10-ca36-4255-b595-70b5b525789c/d7b9ee93-393a-49a0-8f4b-5b4b1f9d83b5?signature=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXRoIjoiLzRjYjZkNDE4LTg2ZWUtNDQyNS1iNWM4LWY5MTI2NmIwYWIyOC82ZDA5ZmYxMC1jYTM2LTQyNTUtYjU5NS03MGI1YjUyNTc4OWMvZDdiOWVlOTMtMzkzYS00OWEwLThmNGItNWI0YjFmOWQ4M2I1IiwiaWF0IjoxNzI3Mzk5MTc5LCJleHAiOjMzMjk3OTU5MTc5fQ.fn7BsaW6DJIlZQj196YTqYZcL8E4f3f6naGJ27B9Izo " alt="CleanShot 2024-09-26 at 21.04.15@2x.png" width="1664" height="784" />

**Comment by samuelstroschein** [comment]
Update: 

The tests are passing now, but a release of Paraglide JS 2.0 is postponed until we have [lix](https://lix.opral.com/) 1.0, which powers Paraglide JS. That's likely in January or February.

- PRs for fixed or improvements will be reviewed and accepted 
- Read more here https://opral.substack.com/p/focus-shift-from-inlang-to-lix

https://github.com/user-attachments/assets/377b2ef3-5fa5-4bca-80c3-8f21bddf0884

**Comment by nosovk** [comment]
it would be nice to also implement something like [that](https://github.com/opral/inlang-paraglide-js/issues/164) in v2

**Comment by samuelstroschein** [comment]
What's this? 👀 _Hint: Work continues. Paraglide JS 2.0 beta this January_ 

![CleanShot 2025-01-03 at 14 11 15@2x](https://github.com/user-attachments/assets/547653f9-c973-40cd-a7ba-5503f10d1974)

**Comment by samuelstroschein** [comment]
## Paraglide JS 2.0 Beta has been released

- variant (plural, gendering, a/b test) support 🥳 
- test the beta and report issues
- targeting general availability by the end of January 

Here are examples to get started https://github.com/opral/monorepo/tree/main/inlang/packages/paraglide-js/examples

https://github.com/user-attachments/assets/c3def77d-60eb-42cf-84ba-4daab3b2de2b

**Comment by nykula** [comment]
I'm very glad that you added a generic form of pluralization using Intl.PluralRules. Reading the examples and documentation, I have some feedback. Sorry if this turns out already covered by your overview video, I can't watch it because of network error. I notice the plurals need a lot of boilerplate:
```
{
"some_happy_cat": {
    "declarations": ["input count", "local countPlural = count: plural"],
    "selectors": ["countPlural"],
    "match": {
      "countPlural=one": "There is one cat.",
      "countPlural=other": "There are many cats.",
    },
  }
}
```
With a note:
```
Read the `local countPlural = count: plural` syntax as "create a local variable `countPlural` that equals `plural(count)`". 
```
Is there a plan to make Paraglide infer the most typical case of declarations and selectors (the one documented) from a shorthand:
```
{
"some_happy_cat": {
    "match": {
      "plural(count)=one": "{count} кіт", // -1 кіт, 21 кіт, 31 кіт...
      "plural(count)=few": "{count} коти", // 2 коти, 22 коти...
      "plural(count)=many": "{count} котів", // 0 котів, 5 котів, 11 котів, 25 котів...
      "plural(count)=other": "{count} кота", // 3,5 кота...
    },
  }
}
```
Otherwise I seem to need a lot of copy-pasting and the translation file will grow vertically way too fast.

**Comment by samuelstroschein** [comment]
@nykula Yes, most inputs are inferred. 

The inlang message format plugin is responsible for the syntax. Any other syntax can be used as well (icu1, i18next, etc.). That said, expressing messages with variants is complex. So complex that we are optimizing for tooling rather than handwriting and managing JSON files.

**Comment by samuelstroschein** [comment]
@gooonzick Yes. I will put updating these docs https://inlang.com/m/gerre34r/library-inlang-paraglideJs/storage-format on my todo list today

**Comment by samuelstroschein** [comment]
updated the docs!

**Comment by samuelstroschein** [comment]
Question about the API. Should Paraglide JS 2.0 

1‍⃣ prefix `locale` suff with "Available" 

```ts
import { availableLocales, type AvailableLocale, assertAvailableLocale } from "./paraglide/runtime.js"

const locale: AvailableLocale = "en"

if (availableLocales.includes("de")){
  //
}

const x = assertAvailableLocale("fr")
```

2‍⃣  or drop the `available` prefix


```ts
import { locales, type Locale, assertLocale } from "./paraglide/runtime.js"

const locale: Locale = "en"

if (locales.includes("de")){
  //
}

const x = assertLocale("fr")
```

Vote with 1‍⃣ for `available` prefix or 2‍⃣ for no prefix

**Comment by samuelstroschein** [comment]
## Progress update

**Jan 12 - Jan 17**

✅ paraglide js 2.0 beta 

✅ astro adapter beta

❌ sveltekit adapter beta

✅ metaframework adapter overhaul approach 

**Focus in Jan 20 - Jan 24**


- sveltekit adapter beta
-  metaframework adapter overhaul implementation 

**Targets for end of january** 

- [on track] GA paraglide js 2.0
- [on track] GA adapters
- [on track] GA metaframework overhaul

https://github.com/user-attachments/assets/399b6095-0470-4534-a463-069f488faa36

**Comment by samuelstroschein** [comment]
**The adapters have been released as beta. Try them out and give feedback.** 

- SvelteKit https://github.com/opral/monorepo/tree/main/inlang/packages/paraglide/paraglide-sveltekit
- NextJS https://github.com/opral/monorepo/blob/main/inlang/packages/paraglide/paraglide-next/example (look into the next.config.js && src/app/layout.tsx) 
- Astro https://github.com/opral/monorepo/tree/main/inlang/packages/paraglide/paraglide-astro

**Target for next week**

- [ ] configurable strategy (i18n routing, cookies, domain based, something else)
- [ ] per locale splitting https://github.com/opral/inlang-paraglide-js/issues/88 
- [ ] https://github.com/opral/inlang-paraglide-js/issues/334

If everything goes well, have the release candidate for paraglide js 2.0 by next Friday 🔥

**Comment by revosw** [comment]
This is an error I am encountering when running `npx next dev` in my Next.js project
```
node:internal/modules/esm/resolve:303
  return new ERR_PACKAGE_PATH_NOT_EXPORTED(
         ^

Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: Package subpath './plugin' is not defined by "exports" in C:\dev\project\node_modules\@inlang\paraglide-next\package.json imported from C:\dev\project\next.config.js
    at exportsNotFound (node:internal/modules/esm/resolve:303:10)
    at packageExportsResolve (node:internal/modules/esm/resolve:650:9)
    at packageResolve (node:internal/modules/esm/resolve:828:14)
    at moduleResolve (node:internal/modules/esm/resolve:918:18)
    at defaultResolve (node:internal/modules/esm/resolve:1148:11)
    at ModuleLoader.defaultResolve (node:internal/modules/esm/loader:528:12)
    at ModuleLoader.resolve (node:internal/modules/esm/loader:497:25)
    at ModuleLoader.getModuleJob (node:internal/modules/esm/loader:231:38)
    at ModuleWrap.<anonymous> (node:internal/modules/esm/module_job:97:39)
    at link (node:internal/modules/esm/module_job:96:36) {
  code: 'ERR_PACKAGE_PATH_NOT_EXPORTED'
}
```

Using `"@inlang/paraglide-js": "2.0.0-beta.13"` and `"@inlang/paraglide-next": "1.0.0-beta.2"`. `1.0.0-beta.1` has the same problem, but `0.7.9` works fine

**Comment by samuelstroschein** [comment]
Can you try renaming your next config to .mjs? I encountered several esm related issues with nextjs that went away after renaming the config to mjs

**Comment by juliomuhlbauer** [comment]
Paraglide supports the next config in .ts?

**Comment by samuelstroschein** [comment]
> Does Paraglide support the next config in .ts?

It should but on my machine a `next.config.ts` led to module resolution errors. 

If you get a `.ts` config to work, make a PR as long as Paraglide JS does not need to be compiled to CJS. Introducing CJS is too much overhead. With the new node feature to import ESM from CJS, the problem might resolve itself.

**Comment by revosw** [comment]
Oh right, I have probably forgotten to read release notes or similar. In my next config I had this:
```ts
import { paraglide } from "@inlang/paraglide-next/plugin";
// ^ note the ./plugin import, hence the error mentioning "./plugin"

export default paraglide({
	paraglide: {
		project: "./project.inlang",
		outdir: "./paraglide",
	},
	// ...other settings
})
```
But now I need to change it to
```
import { withParaglideNext } from "@inlang/paraglide-next";
// ^ removed /plugin, imported the new function

export default withParaglideNext({
	paraglide: {
		project: "./project.inlang",
		outdir: "./paraglide",
	},
	// ...other settings
})
```
I was also amused to see that there were no other exports from the next adapter package, and seemingly no replacement of `<LanguageProvider />`, `useRouter`, `middleware` and other stuff inside paraglide-js.

Despite that, it works flawlessly now!!

**Comment by revosw** [comment]
Acctually, it seems like the default output has changed to `./src/paraglide`, while in my project I used the `./paraglide` path for my output. There is an `--output` option you can run, for example `npx paraglide-js --project my-project.inlang --output ./paraglide`, but I don't see a way to configure the output in the `my-project.inlang/settings.json` file. This means I'll have to run the compiler manually, which is unfortunate

**Comment by samuelstroschein** [comment]
On track for #346: 

https://github.com/user-attachments/assets/d7796593-2d21-4e56-b6d8-3512fbb39c15

**Comment by rorybush** [comment]
I am trying to upgrade to Paraglide V2 with the nextjs adapter but I am currently getting this issue in my middleware.ts file:

```
[{
	"resource": "/Users/User/code/next-project/middleware.ts",
	"owner": "typescript",
	"code": "2307",
	"severity": 8,
	"message": "Cannot find module './paraglide/adapter' or its corresponding type declarations.",
	"source": "ts",
	"startLineNumber": 2,
	"startColumn": 28,
	"endLineNumber": 2,
	"endColumn": 49,
	"modelVersionId": 106
}]
```

I am using the same next config and middleware from this example [https://github.com/opral/monorepo/tree/main/inlang/packages/paraglide/paraglide-next/example](https://github.com/opral/monorepo/tree/main/inlang/packages/paraglide/paraglide-next/example)

```
 "scripts": {
    "dev": "next dev --turbopack",
    "build": "paraglide-js compile --project ./project.inlang --outdir ./paraglide && next build",
    "start": "next start",
    "lint": "next lint",
    "postinstall": "paraglide-js compile --project ./project.inlang --outdir ./paraglide",
    "drizzle": "npx drizzle-kit studio --config drizzle.config.ts"
  },
```

```
  "devDependencies": {
    "@inlang/paraglide-js": "^2.0.0-beta.13",
    "@inlang/paraglide-next": "^1.0.0-beta.2",
```

Any help would be greatly appreciated. Thanks!

**Comment by samuelstroschein** [comment]
Are you using the `withParaglideNext` webpack config? https://github.com/opral/monorepo/blob/main/inlang/packages/paraglide/paraglide-next/example/next.config.mjs

**Comment by ambigos1** [comment]
Hi.
I just wanted to mention that I am getting an Error while running npm install when using the:
    "@inlang/paraglide-js": "2.0.0-beta.14",
    "@inlang/paraglide-sveltekit": "1.0.0-beta.4",

The Error:
npm error Could not resolve dependency:
npm error peer @inlang/paraglide-js@"^2" from @inlang/paraglide-sveltekit@1.0.0-beta.4

![Image](https://github.com/user-attachments/assets/cbd4f819-94fb-4921-9036-3581f989f7e5)

**Comment by samuelstroschein** [comment]
Arghhhhh why are beta releases so broken on NPM? Will fix this today

**Comment by samuelstroschein** [comment]
New batch of beta's released: 

- paraglide js [2.0.0-beta.16](https://www.npmjs.com/package/@inlang/paraglide-js/v/2.0.0-beta.16)
- paraglide next [1.0.0-beta.6](https://www.npmjs.com/package/@inlang/paraglide-next/v/1.0.0-beta.6)
- paraglide astro [1.0.0-beta.4](https://www.npmjs.com/package/@inlang/paraglide-astro/v/1.0.0-beta.4)
- paraglide sveltekit [1.0.0-beta.5](https://www.npmjs.com/package/@inlang/paraglide-sveltekit/v/1.0.0-beta.5)

The new beta's have the #346 API: 

```diff
strategy: ["pathname", "cookie", "baseLocale"]
```

Please try it out and give feedback. If you encounter issues, please open separate issues to keep this thread clean with updates on the beta. 

**Next steps**

- try top level await approach in  #88
- prepare release candidate (docs)

**Comment by mquandalle** [comment]
In the paraglide sveltekit beta, it seems that the logic to replace `%lang%` with the current language in the `app.html` template is gone.

This logic : https://github.com/opral/monorepo/blob/inlang-v1/inlang/source-code/paraglide/paraglide-sveltekit/src/runtime/hooks/handle.server.ts#L162

**Comment by mquandalle** [comment]
Also I can't find the way to translate pathnames in the paraglide sveltekit beta?

**Comment by samuelstroschein** [comment]
@mquandalle see https://github.com/opral/inlang-paraglide-js/issues/359

**Comment by samuelstroschein** [comment]
**Progress on customizable localized pathnames #359  **
 
https://www.loom.com/share/a99cf9e6bf2443bb8f77654828d4640d?sid=7d38e7f1-01fe-4b4c-91b7-9f6c71f51467

API will enable you to match any localized route of your choice. The example below prefixes every path with the locales, even for en. The syntax is uses the web standard URLPattern https://developer.mozilla.org/en-US/docs/Web/API/URL_Pattern_API

```ts
pathnames: {
  "/:path*": {
    en: "/en/:path",
    de: "/de/:path",
  },
},
```

This pattern will not prefix the locale for en 

```ts
pathnames: {
  "/:path*": {
    en: "/:path",
    de: "/de/:path",
  },
},
```

Or go fully custom 

```ts
pathnames: {
  "/blog/:id": {
    en: "/english/blog/:id",
    de: "/deutsch/artikel/:id",
  },
},
```

**Comment by samuelstroschein** [comment]
Gonna go with a bundled version of [path-to-regex](https://www.npmjs.com/package/path-to-regexp) for #359. 

I won't work tomorrow and Thursday on Paraglide 2.0 as I am attending a conference. A release candidate at the end of the week is thereby unlikely but a new beta with the pathname API on Friday is likely. 

https://github.com/user-attachments/assets/1237dffe-99d2-4edf-ba52-dd81bece65a5

**Comment by samuelstroschein** [comment]
### URL based localization (pathname, domain based, multi-tenancy) likely nailed!

I spent over 1 week on coming up with this API, and I think it nails any URL-based use case. Will make a decision tomorrow on whether to use URLPattern or path-to-regexp v8, which depends on https://github.com/pillarjs/path-to-regexp/issues/349

- one API to rule any url based needs 
- not >10 flags are different APIs that interfere in behavior (!) 

**Next steps**

- [ ] determine if path-to-regexp v8 can work with a `baseLocale` setting per pattern to combat ambiguous matches
- [ ] else, try adoption of URLPattern

https://github.com/user-attachments/assets/e4445aff-5255-4af7-b272-8927d96dc232

**Comment by samuelstroschein** [comment]
@nosovk replied in https://github.com/opral/inlang-paraglide-js/issues/164#issuecomment-2657720094

**Comment by samuelstroschein** [comment]
#378 is shipped 🛥. This was the last big development effort that was needed. 

Next up are simple bugfixes or features and write documentation. GA release by the end of February (2 weeks) is on track. 

![Image](https://github.com/user-attachments/assets/f316013a-a683-4589-9f40-0f97b67d20ef)

**Comment by samuelstroschein** [comment]
coming in paraglide js 2.0: 

auto-import when writing `m`. 

no more manual `import * as m`

![Image](https://github.com/user-attachments/assets/37643caa-1988-4ad5-a693-8f8e788a3d45)

**Comment by CanRau** [comment]
That looks fantastic, I'm curious how this works, so far couldn't find anything on how to enable auto-import for `import * as X` 🤔

**Comment by samuelstroschein** [comment]
@zhihengGet you need to use the vite plugin of the adapter for the `adapter.js` file to exist. 

but good news: adapters will likely be a thing of the past today. found another abstraction which makes adapters redundant. will report more later today :)

**Comment by samuelstroschein** [comment]
## Implemented `serverMiddleware()`, no more adapters needed

I shipped #388 which exposes `serverMiddleware()` that works in any SSR framework. No more adapters. You read right. No more adapters. 

- introduced `serverMiddleware()`
- added [examples for frameworks](https://inlang.com/m/gerre34r/library-inlang-paraglideJs/sveltekit), including SSG examples for applicable (closes #109)  

```diff
import type { Handle } from '@sveltejs/kit';
+import { serverMiddleware } from '$lib/paraglide/runtime';

export const handle: Handle = ({ event, resolve }) => {
	return serverMiddleware(event.request, () => resolve(event));
};

```

https://github.com/user-attachments/assets/1a951cfd-681d-4d65-987e-4c0cd6edb69c

Released as beta.19!

**Comment by zhihengGet** [comment]
that is amazing !!! giving it a try now, 

hmm got compile error

in compiled message , the generated export has extra ` at the end

i18n/paraglide/messages/save/es.js
```ts
// eslint-disable

/** @type {(inputs: {}) => string} */
export const Save = () => `Guardar`;`;
```

i have this in my en.json

`	"Save": "Save",`

**Comment by WarningImHack3r** [comment]
The example of @zhihengGet seems to be a bit malformed but I can report a similar issue with the beta 18 I'm playing around with: keys are not clearly marked as case insensitive, which can inadvertently break paraglide exports. On top of that, if you happen to have such issues, you have to manually delete the affected `messages` subfolders to resolve the issue. Can you guys add a clearer warning, not generate these "duplicate" keys and also eventually clean up the `messages` folder with unused localizations?

**Comment by harrytran998** [comment]
Awesome redirect feature @samuelstroschein  - can wait for v2 release

**Comment by samuelstroschein** [comment]
## Nesting and arbitrary key names support implemented

Surprise for v2. Long time awaited nesting of keys is now supported #285. 


```
{
  "nested": {
    "key": "Nested key"
   }
}
```

```ts
import { m } from "./paraglide/messages.js";

console.log(m["nested.key"]());
```

You can even use emojis

```ts
import { m } from "./paraglide/messages.js"

m["🍌"]()

```

**Comment by mquandalle** [comment]
Hi @samuelstroschein, it's great to see the progress with Paraglide v2 lately! I have questions about the api to translate routes:

```js
{
	pattern: ":protocol://:domain(.*)::port?/:about/:path*",
	deLocalizedNamedGroups: { 
		about: "about" 
	},
	localizedNamedGroups: {
		en: { 
			about: "about" 
		},
		fr: { 
			about: "a-propos" 
		},
	},
},
```
 
Is it required to provide a full url pattern with `:protocol://:domain(.*)::port?` even if I just want to specify that "about" is translated to "a-propos" in french?
Does it work with a route param like `/travel-[city]` that I want to translate to `/voyage-[city]`?
Also maybe I read the documentation too quickly but the `deLocalizedNamedGroups` / `localizedNamedGroups` logic isn't clear to me at the moment.

**Comment by samuelstroschein** [comment]
**Paraglide JS GA release this or early next week**

You can adopt Paraglide JS 2.0 already. The latest beta releases are stable. 

The remaining tasks are mostly adding feature for SSG and creating a benchmark suite to test an experimental per locale splitting https://github.com/opral/inlang-paraglide-js/issues/425. Among the open issues: 

- [ ] https://github.com/opral/inlang-paraglide-js/issues/428
- [ ] https://github.com/opral/inlang-paraglide-js/issues/431
- [ ] https://github.com/opral/inlang-paraglide-js/issues/433

**Comment by thankkien** [comment]
> ## Nesting and arbitrary key names support implemented
> Surprise for v2. Long time awaited nesting of keys is now supported [#285](https://github.com/opral/inlang-paraglide-js/issues/285).
> 
> ```
> {
>   "nested": {
>     "key": "Nested key"
>    }
> }
> ```
> 
> import { m } from "./paraglide/messages.js";
> 
> console.log(m["nested.key"]());
> You can even use emojis
> 
> import { m } from "./paraglide/messages.js"
> 
> m["🍌"]()

Hi bro! Nested key are welcome. But I think the variant should be passed through options, right?

![Image](https://github.com/user-attachments/assets/e87125d6-3d89-4b21-acf0-4e57da660203)

![Image](https://github.com/user-attachments/assets/0670c7c0-60aa-4b89-af63-48f4e44b45c7)

**Comment by samuelstroschein** [comment]
@thankkien you need to wrap messages with variants in an array https://inlang.com/m/reootnfj/plugin-inlang-messageFormat#complex-messages-with-variants-pluralization-etc

**Comment by thankkien** [comment]
@samuelstroschein Oh, I was following an expired document here: https://inlang.com/m/gerre34r/library-inlang-paraglideJs/variants

**Comment by samuelstroschein** [comment]
## Two last bugs

- https://github.com/opral/inlang-paraglide-js/issues/411
- https://github.com/opral/inlang-paraglide-js/issues/437

I expect to complete them tomorrow!

Before a 2.0 release, I'd like to complete the following issues as well: 

- #342 
- #444 
- comparison table to other i18n libs
- investigate 1h into per locale splitting via SSG 

PS The >beta.28 are the release candidates. You can go ahead and already adopt it!

**Comment by samuelstroschein** [comment]
Feedback wanted for the comparison table in the docs https://inlang.com/m/gerre34r/library-inlang-paraglideJs#comparison. 

- i find it a bit overwhelming 
- the key message of "paraglide js is simple to use, tree-shakes, and works in any framework" is not getting across
- BUT enterprise adopters are looking for stuff like multi tenancy etc. 

Idea: 

Maybe split the comparison table into two? 1. Simple 5 key features then 2. Full feature comparison (for the people who need it)?

![Image](https://github.com/user-attachments/assets/2a074152-b46e-475c-a917-d3b636db84e7)

**Comment by oskar-gmerek** [comment]
For me personally that table is cool. I would only think about how to visually group that features, this should make reception softer. Maybe something like Basic use | Enterprise use / Advanced use. Maybe the other way... Like Performance, Ecosystem, etc. Something what will visually break long list to the few smaller lists.

**Comment by leeoocca** [comment]
One simple suggestion: the table is not scrollable on mobile, so you can only see the first three columns.

**Comment by 1muen** [comment]
Yes, maybe order/highlight/group the list. We had a preference for a (Meta)framework first and then looked for translation libraries.
So Metaframework (NextJS, SvelteKit, Astro, ...) compatible and Framework agnostic / support for svelte were important.
So grouping Framework stuff like
Metaframework (NextJS, SvelteKit, Astro, ...) compatible and Framework agnostic would make sense.

**Comment by pluxain** [comment]
Hi, thanks for the hard work !

1. I find the "Requires build step" misleading: the "Yes" has the red cross whereas the "No" has the green tick. At first I thought this is just a typo. But probably the icons are OK, but opposite to the answer they represent. So maybe a "No build step" label would be more appropriate: then Paraglide is "No" with red cross and the others are "Yes" with green tick. Or if "Requires a build step" is a "good" thing, then the icons are wrong.
2. I do not find this particularly overwhelming, I just noticed some points are not very clear to me: "Multi-tenancy", "Strategy agnostic" as examples. Maybe an info icon with a tooltip/title which provides context could help.
4. Instead of "Maturity", I would rather use something which is more common and representative like "Under active development". I feel like Maturity term could disadvantage ParaglideJS for no good reason.

**Comment by WarningImHack3r** [comment]
Thank you and congrats for this release!! Hope this will be the new standard for i18n!

**Comment by samuelstroschein** [comment]
@ambios1 you have to create them yourself. you can use this pattern and adapt it for alternate links [https://inlang.com/m/gerre34r/library-inlang-paraglideJs/server-side-rendering#site-crawling-invisible-anchor-tags](https://inlang.com/m/gerre34r/library-inlang-paraglideJs/server-side-rendering#site-crawling-invisible-anchor-tags) or create a sitemap with [https://inlang.com/m/gerre34r/library-inlang-paraglideJs/runtime#generatestaticlocalizedurls](https://inlang.com/m/gerre34r/library-inlang-paraglideJs/runtime#generatestaticlocalizedurls) <br><br>a PR that would introduce a `generateAlternateLinks("/path")` would also be appreciated

**Comment by rickcedwhat** [comment]
Hi @samuelstroschein,

I don't know if I'm referencing the wrong documentation or maybe I have the wrong plugin. I'm trying to include these options but ts is yelling at me saying

> 'options' does not exist in type 'CompilerOptions'

```javascript
// vite.config.ts
import { paraglideVitePlugin } from '@inlang/paraglide-js';

paraglideVitePlugin({
    project: './project.inlang',
    outdir: './src/paraglide',
    // options: {
    //     emitGitIgnore: false,
    //     emitPrettierIgnore: false,
    //     emitDts: true,
    // },
});

**Comment by samuelstroschein** [comment]
@rickcedwhat wrong docs. the options are defined directly on the root object. Please make a PR to the docs to lift the confusion 

```ts

paraglideVitePlugin({
    project: './project.inlang',
    outdir: './src/paraglide',
    //     emitGitIgnore: false,
    //     emitPrettierIgnore: false,
    //     emitDts: true,
});
```

**Comment by Samuel-Morgan-Tyghe** [comment]
Migration Guide from user from I18N who solely use the useTranslation hook.


Example of what i have created, but easily could be added to Paraglide npm


```
// Import the JSON file directly as fallback
import messages from "../../messages/en.json";

// Define TFunction type to maintain compatibility with i18next-based components
export type TFunction<T = any> = (
  key: string,
  options?: Record<string, any>,
) => string;

// Helper function to handle parameter interpolation
const interpolateMessage = (
  message: string,
  options?: Record<string, any>,
): string => {
  if (!options) return message;

  let result = message;
  Object.entries(options).forEach(([key, value]) => {
    // Handle both {key} and {{key}} patterns for compatibility
    result = result.replace(
      new RegExp(`\\{\\{?${key}\\}?\\}`, "g"),
      String(value),
    );
  });

  return result;
};

// Helper function to convert dot notation keys to underscore notation (matching our JSON keys)
const convertKeyToJsonKey = (key: string): string =>
  key
    .replace(/\./g, "_") // dots to underscores
    .replace(/-/g, "_") // hyphens to underscores
    .replace(/[^a-zA-Z0-9_]/g, "_") // any other special chars to underscores
    .replace(/_+/g, "_") // multiple underscores to single
    .replace(/^_|_$/g, ""); // remove leading/trailing underscores

/**
 * @deprecated
 * This custom useTranslation hook is deprecated and will be removed in the future.
 *
 * Please transition to using ParaglideJS message functions directly for all new code.
 * Instead of:
 *   const { t } = useTranslation();
 *   t("subscription.subscriber.general");
 *   t("fileSize.kilobytes", { size: 150 });
 *
 * Use:
 *   import * as m from "@paraglide/messages";
 *   m.subscription_subscriber_general();
 *   m.fileSize_kilobytes({ size: 150 });
 *
 * This provides full type-safety, better performance, and is the recommended approach going forward.
 * See: https://inlang.com/m/gerre34r/library-inlang-paraglideJs/comparison
 */
export const useTranslation = () => {
  const t: TFunction = (key: string, options?: Record<string, any>) => {
    // First try the key as-is
    let message = (messages as any)[key];

    // If not found, try converting dots to underscores
    if (!message) {
      const convertedKey = convertKeyToJsonKey(key);
      message = (messages as any)[convertedKey];
    }

    // If still not found, try some variations
    if (!message) {
      const variations = [
        key.toLowerCase(),
        key.toUpperCase(),
        convertKeyToJsonKey(key.toLowerCase()),
        convertKeyToJsonKey(key.toUpperCase()),
      ];

      for (const variation of variations) {
        if ((messages as any)[variation]) {
          message = (messages as any)[variation];
          break;
        }
      }
    }

    if (message) {
      // Interpolate parameters if provided
      return interpolateMessage(message, options);
    }

    // If no message found, log a warning and return the key
    console.warn(`Translation key not found: ${key}`);

    return key;
  };

  return { t };
};

```

**Comment by samuelstroschein** [comment]
@qshssewww no. the idea is that the *.inlang folder is under our control. otherwise, we'd have to consider how users interact witht that dir and what is gitignored etc
