### ISSUE TITLE
add option to disable async local storage in astro

### ISSUE THREAD

**Issue by samuelstroschein** [opral/inlang-paraglide-js#265]
### Context

The Astro adapter doesn't work when deploying to cloudflare workers.

Serverless environments like Cloudflare workers have no risk of cross request problems. Async Local Storage, which is used to avoid cross request bugs in the Astro adapter, is not needed in those environments and also not available. 

### Proposal

Add an option to disable AsyncLocalStorage similar to the SvelteKit adapter [https://github.com/opral/inlang-paraglide-js/issues/163#issuecomment-2509799621](https://github.com/opral/inlang-paraglide-js/issues/163#issuecomment-2509799621). 

### Tasks

- [ ] add option in the paraglide astro integration `disableAsyncLocalStorage` 

```diff
integrations: [
	paraglide({
		// recommended settings
		project: "./project.inlang",
		outdir: "./src/paraglide",
+       disableAsyncLocalStorage: true
	}),
],
```

- [ ] create a new `middleware-no-async-local-storage` similar to [https://github.com/opral/monorepo/blob/39c013d01e6134fc5ad07818949e260fc815abba/inlang/source-code/paraglide/paraglide-astro/src/middleware.ts#L1-L82](https://github.com/opral/monorepo/blob/39c013d01e6134fc5ad07818949e260fc815abba/inlang/source-code/paraglide/paraglide-astro/src/middleware.ts#L1-L82) but without relying on async local storage
- [ ] use `config.disableAsyncLocalStorage` in [integration.ts](https://github.com/opral/monorepo/blob/39c013d01e6134fc5ad07818949e260fc815abba/inlang/source-code/paraglide/paraglide-astro/src/integration.ts#L22-L26) to resolve the middleware

```diff
export function integration(integrationConfig: {
	project: string
	outdir: string
+   disableAsyncLocalStorage: boolean
}): AstroIntegration {
	return {
		name: "paraglide",
		hooks: {
			"astro:config:setup": async ({ addMiddleware, updateConfig, injectScript }) => {
				//Register the middleware
				addMiddleware({
					order: "pre", //Run before user-defined middleware (why not?)
-					entrypoint: middlewarePath,
+                   entrypoint: disableAsyncLocalStorage ? middlewarePathNoAsyncLocalStorage : middlewarePath
				})
```

- [ ] update documentation to explain that async local storage can be disabled for cloudflare workers

**Comment by samuelstroschein** [comment]
Workaround exists in Paraglied JS 2.0. See https://github.com/opral/monorepo/commit/45552a35945552cbd8bea87fce5c35282022c3dd
