### ISSUE TITLE
remove `allowJs` from `paraglide js init` command

### ISSUE THREAD

**Issue by samuelstroschein** [opral/inlang-paraglide-js#283]
### Context

With [https://github.com/opral/inlang-paraglide-js/issues/282](https://github.com/opral/inlang-paraglide-js/issues/282) it becomes possible to emit declaration files next to the JSDoc. The need to set `allowJs` in the package.json is not required when emitting declaration files. 

### Proposal 

Ease the Paraglide JS setup by emitting declaration files by default and remove the need to set `allowJs` during the init process. 

#### Tasks

- [ ] emit declaration files by default
- [ ] remove allowJs package json mod in init
- [ ] remove JSON5 dependency
- [ ] update documentation

**Comment by samuelstroschein** [comment]
declarations lead to decreased DX. Closing this in favor of [https://github.com/opral/inlang-paraglide-js/issues/299](https://github.com/opral/inlang-paraglide-js/issues/299)
